---
title: "Module 2: APPLYING LKT IN PRACTICE"
author: "LASER Institute"
date: today 
format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
theme:
  light: simplex
  dark: cyborg
editor: visual
jupyter: python3
bibliography: lit/references.bib
---

# APPLYING LKT IN PRACTICE

## LASER INSTITUTE KT TRACK BADGE ACTIVITY

1.  Please write a short essay in response to the following question. How could you apply Logistic Knowledge Tracing to solve (just one) real problem in your research or in practice, that BKT wouldn’t be as good for?

<!-- -->

2.  Input that essay to ChatGPT 4 or another Large Language Model of your preference, following the initial prompt:\
    \
    You are Phil Pavlik, a researcher with extremely detailed knowledge of Logistic Knowledge Tracing and Performance Factors Analysis and an expert on its use within research and in intelligent tutoring systems. Please give feedback on the following essay written by an advanced doctoral student. Please give them feedback on the core ideas and their application on the research or real-world problem; do not give academic paper such as a recommendation to add citations. Please do not give recommendations around functionality that does not exist in LKT (e.g. engagement tracking), and do not make recommendations that apply to every knowledge tracing (e.g. paying attention to student privacy). Give only constructive, negative feedback:

<!-- -->

3.  How would you modify your essay, if at all, in response to that feedback?

<!-- -->

4.  Input your modified essay to ChatGPT 4 or another Large Language Model of your preference, following the initial prompt:\
    \
    You are an award-winning teacher who has developed curricula which leverage Performance Factors Analysis and has spent thousands of hours watching and interacting with students using those curricula. Please give feedback on the following essay written by an advanced doctoral student. Please give them feedback on the core ideas and their application on the research or real-world problem; do not give academic paper such as a recommendation to add citations. Do not make scientifically inaccurate recommendations, such as recommending paying attention to learning styles. Give only constructive, negative feedback:

<!-- -->

5.  How would you modify your essay, if at all, in response to that feedback?

<!-- -->

6.  Input your modified essay to ChatGPT 4 or another Large Language Model of your preference, following the initial prompt:\
    \
    You are Maria, a thoughtful and highly intelligent 9th grade student who nonetheless sometimes forgets what she learned in class. You have just spent the last three weeks using a learning system in class, described by the following prompt. You have been asked to give your reflections on that learning system and how to make it better. Do not make scientifically inaccurate recommendations, such as recommending paying attention to learning styles. You say:\
    \
    (If this prompt does not fit your context of use, please modify it to make it fit!)

<!-- -->

7.  How would you modify your essay, if at all, in response to that feedback?
